INSERT INTO `tbl_category` (`id`, `name`) VALUES ('1', 'Appliance');
INSERT INTO `tbl_category` (`id`, `name`) VALUES ('2', 'Automotive Accessories');
INSERT INTO `tbl_category` (`id`, `name`) VALUES ('3', 'Babies & Kids');
INSERT INTO `tbl_category` (`id`, `name`) VALUES ('4', 'Beauty Products');
INSERT INTO `tbl_category` (`id`, `name`) VALUES ('5', 'Cars');
INSERT INTO `tbl_category` (`id`, `name`) VALUES ('6', 'Electronics');
INSERT INTO `tbl_category` (`id`, `name`) VALUES ('7', 'Finance');
INSERT INTO `tbl_category` (`id`, `name`) VALUES ('8', 'Furniture & Bedding');
INSERT INTO `tbl_category` (`id`, `name`) VALUES ('9', 'Garden & Power Tools');
INSERT INTO `tbl_category` (`id`, `name`) VALUES ('10', 'Home Care');
INSERT INTO `tbl_category` (`id`, `name`) VALUES ('11', 'Insurance');
INSERT INTO `tbl_category` (`id`, `name`) VALUES ('12', 'Kitchenware');
INSERT INTO `tbl_category` (`id`, `name`) VALUES ('13', 'Motorbike');
INSERT INTO `tbl_category` (`id`, `name`) VALUES ('14', 'Pet Products');
INSERT INTO `tbl_category` (`id`, `name`) VALUES ('15', 'Services');
INSERT INTO `tbl_category` (`id`, `name`) VALUES ('16', 'Shops');
INSERT INTO `tbl_category` (`id`, `name`) VALUES ('17', 'Travel Services');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('18', 'Air Conditioners', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('19', 'Air Fryers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('20', 'Air Purifiers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('21', 'All-In-One Kitchen Appliances', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('22', 'BBQs', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('23', 'Bar & Wine Fridges / Refrigerators', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('24', 'Benchtop / Toaster Ovens', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('25', 'Blenders', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('26', 'Bread Makers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('27', 'Clothes Dryers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('28', 'Coffee Grinders / Roasters', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('29', 'Coffee Machines', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('30', 'Cooktops', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('31', 'Deep Fryers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('32', 'Dehumidifiers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('33', 'Dishwashers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('34', 'Electric Skillets and Works', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('35', 'Fans', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('36', 'Food Dehydrantors', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('37', 'Food Mixers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('38', 'Food Processors', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('39', 'Food Sealer', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('40', 'Food Steamers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('41', 'Freezers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('42', 'Fridges / Refrigerators', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('43', 'Garment Steamers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('44', 'Grills', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('45', 'Heaters', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('46', 'Hot Water System', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('47', 'Humidifiers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('48', 'Ice Cream Makers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('49', 'Irons & Steam Generators', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('50', 'Juicers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('51', 'Kettles', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('52', 'Microwaves', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('53', 'Milk Frothers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('54', 'Multi Cookers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('55', 'Novelty / Snack Makers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('56', 'Ovens', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('57', 'Pasta Makers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('58', 'Portable Fridges / Freezers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('59', 'Pressure Cookers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('60', 'Range Hoods', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('61', 'Rice Cookers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('62', 'Sandwich Makers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('63', 'Sewing Machines & Overlockers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('64', 'Slow Cookers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('65', 'Soup Makers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('66', 'Steam Cleaners', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('67', 'Steam Mops', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('68', 'Stick Blenders / Mixers', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('69', 'Toasters', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('70', 'Vacuum Cleaners', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('71', 'Washing Machines', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('72', 'Water Filters', '1');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('73', 'Car Accessories', '2');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('74', 'Car Care Products', '2');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('75', 'Car Stereos', '2');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('76', 'Dash Cams', '2');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('77', 'Engine Oils', '2');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('78', 'GPS NavigationSystems', '2');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('79', 'Reversing Cameras', '2');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('80', 'Types', '2');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('81', 'Baby Carriers', '3');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('82', 'Baby Feeding Products', '3');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('83', 'Baby Health & Hygiene Products', '3');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('84', 'Baby Nappies', '3');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('85', 'Baby: At Home', '3');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('86', 'Baby: Home Safey', '3');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('87', 'Car Seats', '3');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('88', 'Best Pram & Stroller Accessories', '3');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('89', 'Maternity Products', '3');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('90', 'Prams & Strollers', '3');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('91', 'Toys & Games', '3');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('92', 'Trampolines', '3');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('93', 'Body Care Products', '4');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('94', 'Fragrances', '4');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('95', 'Hair Care Products', '4');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('96', 'Make-Up & Cosmetic Products', '4');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('97', 'Make-Up Removers', '4');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('98', 'Personal Care & Hygiene', '4');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('99', 'Convertibles', '5');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('100', 'Hatchbacks', '5');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('101', 'People Movers', '5');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('102', 'SUVs / 4WDs', '5');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('103', 'Sedans', '5');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('104', 'Sports Cars', '5');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('105', 'Utes', '5');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('106', 'Vans', '5');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('107', 'Wagons', '5');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('108', 'Blu-Ray & DVD Players', '6');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('109', 'Digital Cameras', '6');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('110', 'Headphones', '6');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('111', 'Home Audio Products', '6');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('112', 'Home Phones', '6');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('113', 'Laptops', '6');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('114', 'Mobile Phones', '6');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('115', 'Modems / Routers', '6');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('116', 'Printers', '6');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('117', 'Set Top Boxes / PVRs / DVRs', '6');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('118', 'TVs', '6');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('119', 'Tablets', '6');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('120', 'Bank Accounts', '7');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('121', 'Banks', '7');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('122', 'Buy Now, Pay Later Services', '7');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('123', 'Credit Cards', '7');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('124', 'Financial Services', '7');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('125', 'Insurances', '7');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('126', 'Loans', '7');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('127', 'Rewards & Loyalty Programs', '7');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('128', 'Bedding Products', '8');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('129', 'Furniture', '8');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('130', 'Lawn Care & Maintenance Tools', '9');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('131', 'Pool Cleaners', '9');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('132', 'Lawn Movers', '9');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('133', 'Power Tools', '9');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('134', 'Air Fresheners & Deodorisers', '10');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('135', 'All Purpose Cleaners', '10');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('136', 'Bathroom & Toilet Cleaners', '10');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('137', 'Brooms & Brushes', '10');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('138', 'Carpet & Floor Cleaners', '10');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('139', 'Dishwashing Products', '10');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('140', 'Home Security Products', '10');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('141', 'Laundry Detergents', '10');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('142', 'Mops & Buckets', '10');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('143', 'Oven & Cooktop Cleaners', '10');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('144', 'Paints & Varnishes', '10');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('145', 'Pest Control Products', '10');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('146', 'Business Insurance', '11');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('147', 'Car Insurance', '11');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('148', 'Health Insurance', '11');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('149', 'Home & Contents Insurance', '11');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('150', 'Life Insurance', '11');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('151', 'Travel Insurance', '11');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('152', 'Baking Dishes', '12');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('153', 'Cookware & Fryware Products', '12');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('154', 'Dicers & Choppers', '12');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('155', 'Faucets / Tap Mixers', '12');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('156', 'Food Mincers', '12');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('157', 'Food Storage Containers', '12');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('158', 'Kitchen Knives', '12');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('159', 'Kitchen Slicers & Graters', '12');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('160', 'Knife Sharpener', '12');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('161', 'Serveware Products', '12');
INSERT INTO `tbl_category` (`id`, `name`, `parent_id`) VALUES ('162', 'Sinks', '12');